//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lekan_Donation.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Signup
    {
        public int Id { get; set; }
        [Required(ErrorMessage =" Your First Name is Required"),MaxLength(20)]
        [Display(Name ="First Name")]
        [DataType(DataType.Text)]
        public string First_name { get; set; }
        [Required(ErrorMessage = " Your Last Name is Required"), MaxLength(20)]
        [Display(Name = "Last Name")]
        [DataType(DataType.Text)]
        public string Last_name { get; set; }
        [Required(ErrorMessage = " Your Age is Required"), MaxLength(3)]
        [Display(Name = "Age")]
        public string Age { get; set; }
        [Required(ErrorMessage = " Your Gender is Required"), MaxLength(6)]
        [Display(Name = "Gender")]
        [DataType(DataType.Text)]
        public string Gender { get; set; }
        //[Required(ErrorMessage = " Your Email is Required"), MaxLength(30)]
        [RegularExpression(@"^\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*$", ErrorMessage = "Email is not valid."),MaxLength(30)]
        [Display(Name = "E-mail")]
        [DataType(DataType.EmailAddress)]
        public string E_mail { get; set; }
        [Required(ErrorMessage = "Please enter Mobile No")]
        [Display(Name = "Contact Number")]
        [DataType(DataType.PhoneNumber)]
        public string phone_no { get; set; }
        [Required(ErrorMessage = " Your Gender is Required"), MaxLength(256)]
        [Display(Name = "Address")]
        [DataType(DataType.Text)]
        public string Address { get; set; }
        [Required(ErrorMessage = "Your Date of Birth is Required")]
        [Display(Name = "Date of Birth")]
        [DataType(DataType.Date)]
        public System.DateTime DOB { get; set; }
        [Required(ErrorMessage = " Your Country is Required"), MaxLength(20)]
        [Display(Name = "Country")]
        [DataType(DataType.Text)]
        public string Nationality { get; set; }
    }
}
